name: Pull Request Checks
on: pull_request
jobs:
  Rust-tests-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "--deny warnings"
